### ISSUE TITLE
Negative candidates in the implementation are different than the ones proposed in the paper

### ISSUE THREAD

**Issue by katie-cathy-hunt** [facebookresearch/unlikelihood_training#1]
According to the paper, the negative candidates for a timestep are **previous context tokens** excluding the target token for that timestep.

<img width="971" alt="image" src="https://user-images.githubusercontent.com/57769557/68884776-b8179300-06c8-11ea-98ec-5facf59f24cd.png">

However, according to the implementation, the negative candidates for a timestep are all tokens in the vocabulary excluding the target token for that timestep.

https://github.com/facebookresearch/unlikelihood_training/blob/723747171a3fa909cda68df399e39f0a3e5067d9/custom/candidate_penalty_ce_loss.py#L44

1. Do both approaches achieve the same result?
2. The implementation seems to be less efficient since it has to take into account all tokens in the vocabulary instead of just the previous context tokens, right?

Thanks.

**Comment by uralik** [comment]
The implementation of the loss corresponds to the paper.

We compute a mask (`negative_targets`) to select negative candidates, and then multiply whole vocab vector (`one_minus_probs`) with that mask.

You can check it here:
https://github.com/facebookresearch/unlikelihood_training/blob/723747171a3fa909cda68df399e39f0a3e5067d9/custom/candidate_penalty_ce_loss.py#L50-L59

**Comment by uralik** [comment]
I am closing this issue now, feel free to re-open for further questions!
